- hosts: all

  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: wartest
        state: stopped

    - name: Remove containers
      docker_container:
        name: wartest
        state: absent
